---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - session.autodev
  resources:
  - devsessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - session.autodev
  resources:
  - devsessions/finalizers
  verbs:
  - update
- apiGroups:
  - session.autodev
  resources:
  - devsessions/status
  verbs:
  - get
  - patch
  - update
