apiVersion: session.autodev/v1
kind: DevSession
metadata:
  labels:
    app.kubernetes.io/name: devsession
    app.kubernetes.io/instance: devsession-sample
    app.kubernetes.io/part-of: autodev-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: autodev-operator
  name: devsession-sample
spec:
  useide: true
  persistant: true
  active: true
  podspec:
    containers:
      - name: code
        image: linuxserver/code-server:latest
        ports:
        - containerPort: 8443
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: Etc/UTC
          - name: PASSWORD
            value: secret
          - name: SUDO_PASSWORD
            value: secret
