apiVersion: session.autodev/v1
kind: DevSession
metadata:
  labels:
    app.kubernetes.io/name: devsession
    app.kubernetes.io/instance: devsession-sample
    app.kubernetes.io/part-of: autodev-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: autodev-operator
  name: devsession-sample
spec:
  useide: true
  persistant: true
  active: true
  podspec:
    containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
